### ISSUE TITLE
exact match problem

### ISSUE THREAD

**Issue by romisfrag** [davemolk/dorking#1]
Hello, 
Thank you a lot for this tool. 
I've tryed to perform some tasks with it and it seem's that some dorks arrent working
for example if i wan't to search with inurl `dorking -exact -j -v -w -inurl drive.google.com -q 'johndoe`
The request for example to duck duck go is `https://html.duckduckgo.com/html?q="johndoe"+inanchor%3Adrive.google.com` which produce this search `"johndoe" inanchor:drive.google.com` 
Which is not going to find what I wan't because inanchor does not work with duck duck go. It should produce this search `"johndoe" inurl:"drive.google.com"` (with the quote arround drive.google.com because duck duck go will not match good result if not.

**Comment by romisfrag** [comment]
And for example in bing this is not inanchor but instreamset: https://learn.microsoft.com/en-us/previous-versions/bing/search/ff795650(v=msdn.10)?redirectedfrom=MSDN

**Comment by davemolk** [comment]
Thanks for raising these points (and sorry I somehow botched that duck duck go inurl, yikes). 

For bing, the first page of search results for instreamset:(url):soccer and inanchor:soccer are nearly identical, and all results for each of those contains the word "soccer" in the url. Is there a reason to use instreamset over inanchor in this particular case?

I'll get these changes merged in the next few days. Thanks so much for bringing them to my attention, and please let me know if there's more you notice (or want to see). I wanted to get essentially a beta out there but plan on coming back and adding more sophisticated query possibilities.

**Comment by davemolk** [comment]
fixed up the duck duck go -- thanks again for bringing this to my attention
